---
- name: install docker by using ansible
  hosts: all
  become: yes
  tasks:
    - name: install java using ansible
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
    - name: install docker packages
      apt:
        name: docker.io
        state: present
    - name: start docker
      service:
        name: docker
        state: started
    - name: copy docker file from master to slave
      copy:
        src: /home/ubuntu/Dockerfile
        dest: /home/ubuntu

    - name: build docker image
      command: docker build -t manasa .
      args:
        chdir: /home/ubuntu
    - name: tag docker image
      command: docker tag manasa 78931/sc
    - name: docker login
      docker_login:
        username: 78931
        password: Manasa.Sc1
    - name: push docker image
      command: docker push 78931/sc
...
